Repository phovea/phovea_clue, pull requests merged in 2019-12, with the labels that each got.

#158 Update template files and dependencies
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .yo-rc.json
  buildInfo.js
  buildPython.js
  deploy/docker-compose.partial.yml
  package.json
  setup.py
  webpack.config.js
Labels: release: major, type: technical debt

#155 Close dialog for editing node in Provenance graph after click on…
  src/provvis.ts
Labels: priority: low, release: patch, type: bug

#159 Change css filename from `style` to `[name]` in webpack.config.js
  package-lock.json
  webpack.config.js
Labels: release: patch, type: technical debt

#156 Add I18N support and extract language strings
  package-lock.json
  phovea.js
  phovea_registry.js
  src/ACLUEWrapper.ts
  src/CLUEGraphManager.ts
  src/annotation.ts
  src/assets/locales/en/phovea.json
  src/menu/ProvenanceGraphMenu.ts
  src/mode.ts
  src/phovea.ts
  src/provvis.ts
  src/storyvis.ts
  tsconfig.json
Labels: release: minor, type: feature

#153 Add typings for provenance graph extension point
  src/ACLUEWrapper.ts
  src/extensions.ts
Labels: release: patch, type: refactor

#161 Release 3.0.0
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .yo-rc.json
  buildInfo.js
  buildPython.js
  deploy/docker-compose.partial.yml
  package-lock.json
  package.json
  phovea.js
  phovea_registry.js
  requirements.txt
  setup.py
  src/ACLUEWrapper.ts
  src/CLUEGraphManager.ts
  src/annotation.ts
  src/assets/locales/en/phovea.json
  src/extensions.ts
  src/menu/ProvenanceGraphMenu.ts
  src/mode.ts
  src/phovea.ts
  src/provvis.ts
  src/storyvis.ts
  tsconfig.json
  webpack.config.js
Labels: release: major
